name: Pipeline CI-CD

on:
  push:
    branches: [ principal, main ]
  pull_request:
    branches: [ principal, main ]

jobs:
  continuous-integration:
    name: Build & Test (CI)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Executar Testes Automatizados
        run: |
          python -c "print('CI: Testes de codigo executados com sucesso!')"

  continuous-deployment:
    name: Deploy Application (CD)
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Simular Deploy em Producao
        run: |
          echo "CD: Aplicacao implantada com sucesso no ambiente de producao!"
